### PR TITLE
update npm scripts for windows compatibility

### PR DESCRIPTION
**Pull request by krisaoe**
"set" command required to set environment variables in windows,
two ampersands to conditionally run commands in sequence

### CODE REVIEW

**Comment by verekia** [comment]
Unfortunately, this does not work on Unix / Mac.
```sh
$ set NODE_ENV=production&& node
> process.env.NODE_ENV
undefined
```
I'll think of an alternative solution. Thank you for bringing up this issue!

**Comment by verekia** [comment]
Solved by using 2 different webpack config files.

**Comment by krisaoe** [comment]
Ah! That struck me as I was going to sleep.
I've been considering cross-env and better-npm-run, although both have their drawbacks imo.
I just came across this fork of bnr [Redisrupt/better-npm-run](https://github.com/Redisrupt/better-npm-run) which might be useful.
I look forward to reading your solution.

**Comment by verekia** [comment]
`cross-env` is exactly what we need. I think I'll use this :)

**Comment by krisaoe** [comment]
Great! I'll get to learn how to use the best of the bunch :biggrin:

**Comment by krisaoe** [comment]
to clarify: I think the 'drawbacks' I mentioned were more a lack of understanding of the docs I could find on the packages

**Comment by verekia** [comment]
@krisaoe If you have access to a Windows environment, could you help me test it out?

There is a branch ready using `cross-env`: https://github.com/verekia/js-stack-boilerplate/tree/enhancement/cross-env

If you could clone that branch, and try to build dev and prod, that would be great :)

For dev we're expecting Webpack-dev-server to generate 2 large files (1.5Mo+) with sourcemaps, and for prod we should be getting just the 330kb bundle.

**Comment by krisaoe** [comment]
Love to help. I'm a bit new, so if there's anything I miss/mess just tell me

**Comment by verekia** [comment]
@krisaoe In a new folder, run the following:
```sh
git clone https://github.com/verekia/js-stack-boilerplate.git
cd js-stack-boilerplate
git checkout enhancement/cross-env
yarn
yarn start
-> Check that the 2 big files are generated, then press Ctrl+C to interrupt
yarn run prod
-> Check that webpack only generates dist/js/bundle.js  332 kB
```
That's should do it :)

**Comment by krisaoe** [comment]
Sorry, I didn't see your reply in time!
I cloned the branch, and tried the test script first, which failed, due to the windows linebreak styles

**Comment by krisaoe** [comment]
```
   5:17  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:45  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:77  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:73  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:2   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 313 problems (313 errors, 0 warnings)

error Command failed with exit code 1.
error Command failed with exit code 1.
```

**Comment by krisaoe** [comment]
so I changed eslintrc to:

```json
"rules": {
    "semi": [2, "never"],
    "no-unexpected-multiline": 2,
    "linebreak-style": [
      "error",
      "windows"
    ]
  }
```

**Comment by krisaoe** [comment]
and tests run nicely
not sure if those rules work with unix/mac linebreaks

**Comment by krisaoe** [comment]
just ran full-check:

```
yarn full-check v0.19.1
$ yarn test && yarn prod && yarn stop
yarn test v0.19.1
$ yarn lint && flow && jest --coverage
yarn lint v0.19.1
$ eslint src webpack.config.babel.js --ext .js,.jsx
Done in 2.35s.
Launching Flow server for E:\Projects\js-stack-boilerplate
Spawned flow server (pid=8612)
Logs will go to C:\Users\agent\AppData\Local\Temp\flow\EzCzBProjectszBjs-stack-boilerplate.log
?[0KNo errors!ill initializing; this can take some time. [merging inference] \
 PASS  src\client\reducer\dog.test.js
 PASS  src\client\action\dog.test.js
----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |      100 |      100 |      100 |      100 |                |
 client/action  |      100 |      100 |      100 |      100 |                |
  dog.js        |      100 |      100 |      100 |      100 |                |
 client/reducer |      100 |      100 |      100 |      100 |                |
  dog.js        |      100 |      100 |      100 |      100 |                |
 shared         |      100 |      100 |      100 |      100 |                |
  routes.js     |      100 |      100 |      100 |      100 |                |
----------------|----------|----------|----------|----------|----------------|

Test Suites: 2 passed, 2 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        1.539s, estimated 2s
Ran all test suites.
Done in 47.98s.
yarn prod v0.19.1
$ yarn stop && yarn build && pm2 start pm2-prod.yaml
yarn stop v0.19.1
$ rimraf logs/* && pm2 delete all || true

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.4.0
Local PM2 version: 2.3.0

[PM2] Applying action deleteProcessId on app [all](ids: 0)
[PM2] [server](0) ✓
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Done in 7.12s.
yarn build v0.19.1
$ rimraf dist lib && cross-env NODE_ENV=production webpack -p --progress && babel src/server -d lib/server --igno

re test.js && babel src/shared -d lib/shared --ignore test.js
Hash: 4ce9599021ffe992817b
Version: webpack 2.2.1
Time: 7005ms
            Asset    Size  Chunks                    Chunk Names
dist/js/bundle.js  332 kB       0  [emitted]  [big]  main
  [54] ./~/react/react.js 56 bytes {0} [built]
  [79] (webpack)/buildin/global.js 509 bytes {0} [built]
  [96] ./~/react-redux/es/index.js 194 bytes {0} [built]
 [152] ./~/redux/es/index.js 1.08 kB {0} [built]
 [232] ./~/redux/es/createStore.js 8.79 kB {0} [built]
 [234] ./src/client/container/bark-buttons.js 715 bytes {0} [built]
 [235] ./src/client/container/bark-message.js 539 bytes {0} [built]
 [236] ./src/client/reducer/dog.js 1.19 kB {0} [built]
 [237] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [238] ./~/react-dom/index.js 59 bytes {0} [built]
 [239] ./~/redux-thunk/lib/index.js 529 bytes {0} [built]
 [423] ./~/core-js/shim.js 7.38 kB {0} [built]
 [437] ./~/immutable/dist/immutable.js 142 kB {0} [built]
 [577] ./~/regenerator-runtime/runtime.js 22.5 kB {0} [built]
 [582] ./src/client/entry.jsx 1.46 kB {0} [built]
    + 568 hidden modules
src\server\index.js -> lib\server\index.js
src\server\require-hook.js -> lib\server\require-hook.js
src\server\template\master-template.js -> lib\server\template\master-template.js
src\shared\config.js -> lib\shared\config.js
src\shared\routes.js -> lib\shared\routes.js
Done in 14.33s.

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.4.0
Local PM2 version: 2.3.0

[PM2][WARN] Applications prod not running, starting...
[PM2][WARN] Folder does not exists: logs
[PM2] Creating folder: logs
[PM2] App [prod] launched (1 instances)
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ prod     │ 0  │ fork │ 30248 │ online │ 0       │ 2s     │ 75% │ 18.6 MB   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Done in 28.01s.
yarn stop v0.19.1
$ rimraf logs/* && pm2 delete all || true

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.4.0
Local PM2 version: 2.3.0

[PM2] Applying action deleteProcessId on app [all](ids: 0)
[PM2] [prod](0) ✓
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Done in 7.48s.
Done in 87.15s.
```

**Comment by krisaoe** [comment]
and now i will run start script
if the order i ran scripts affects the output, i can start again?

**Comment by krisaoe** [comment]
```
yarn start v0.19.1
$ yarn dev
yarn dev v0.19.1
$ yarn stop && pm2 start pm2-dev.yaml && webpack-dev-server --progress
yarn stop v0.19.1
$ rimraf logs/* && pm2 delete all || true

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.4.0
Local PM2 version: 2.3.0

[PM2][WARN] No process found
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Done in 2.61s.

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.4.0
Local PM2 version: 2.3.0

[PM2][WARN] Applications dev not running, starting...
[PM2] App [dev] launched (1 instances)
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬──────┬───────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu  │ mem       │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼──────┼───────────┼──────────┤
│ dev      │ 0  │ fork │ 3372 │ online │ 0       │ 3s     │ 112% │ 29.6 MB   │ enabled  │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴──────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
 10% building modules 1/1 modules 0 active
Project is running at http://localhost:7000/
webpack output is served from /
Hash: a609ba40618494cfe0d8
Version: webpack 2.2.1
Time: 3707ms
                Asset     Size  Chunks                    Chunk Names
    dist/js/bundle.js  1.53 MB       0  [emitted]  [big]  main
dist/js/bundle.js.map  1.84 MB       0  [emitted]         main
chunk    {0} dist/js/bundle.js, dist/js/bundle.js.map (main) 1.44 MB [entry] [rendered]
   [76] ./~/react/react.js 56 bytes {0} [built]
  [162] ./~/react-redux/es/index.js 194 bytes {0} [built]
  [253] ./~/redux/es/index.js 1.08 kB {0} [built]
  [268] ./src/client/entry.jsx 1.46 kB {0} [built]
  [269] (webpack)-dev-server/client?http://localhost:7000 4.66 kB {0} [built]
  [274] ./src/client/container/bark-message.js 539 bytes {0} [built]
  [275] ./src/client/reducer/dog.js 1.19 kB {0} [built]
  [277] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
  [530] ./~/react-dom/index.js 59 bytes {0} [built]
  [627] ./~/redux-thunk/lib/index.js 529 bytes {0} [built]
  [659] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [664] ./~/url/url.js 23.3 kB {0} [built]
  [666] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [668] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [670] multi (webpack)-dev-server/client?http://localhost:7000 ./src/client/entry.jsx 40 bytes {0} [built]
     + 656 hidden modules
webpack: Compiled successfully.
```

**Comment by verekia** [comment]
That is perfect, thank you very much. `cross-env` works as expected.
Thank you for the ESLint thing as well, I'll add a comment in the tutorial :)

**Comment by krisaoe** [comment]
I just noticed the in-memory pm2 is out of date - i'll update as suggested.
Is this important?

**Comment by verekia** [comment]
No it's okay, well at least it's not an issue for this tutorial ;) You can update it for your own usage though.

**Comment by krisaoe** [comment]
If anyone has trouble, i had to invoke `pm2 update` using `./node_modules/.bin/pm2 update`
start script output is identical

**Pull request closed without merging**
